In [7]:
import torch as t

In [8]:
#number
t1=t.tensor(4.)
t1

tensor(4.)

In [9]:
#vector
t2=t.tensor([5.,3,8])
t2

tensor([5., 3., 8.])

In [10]:
t2.shape

torch.Size([3])

In [11]:
t2.dtype

torch.float32

In [12]:
#matrix
t3=t.tensor([[3,4],[2,6],[7,4]])
t3

tensor([[3, 4],
        [2, 6],
        [7, 4]])

In [13]:
#size property
t3.shape

torch.Size([3, 2])

In [14]:
#3d array
t4=t.tensor([[[11,12,13],[22,33,44]],[[21,24,45],[33,34,56]]])
t4

tensor([[[11, 12, 13],
         [22, 33, 44]],

        [[21, 24, 45],
         [33, 34, 56]]])

In [15]:
print(t4)
t4.shape

tensor([[[11, 12, 13],
         [22, 33, 44]],

        [[21, 24, 45],
         [33, 34, 56]]])


torch.Size([2, 2, 3])

In [16]:
t4.dtype

torch.int64

Tensor operatins and gradients
we can combine tensors with the usual arithmetic operations

In [17]:
#create tensors
x=t.tensor(3.)
w=t.tensor(4.,requires_grad=True)
b=t.tensor(5.,requires_grad=True)

In [18]:
#arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [19]:
#cmpute derivatives
y.backward()

In [20]:
#display gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


Interoperabiity with Numpy


In [21]:
import numpy as np 
x = np.array([[1,2],[3,4.]])
x

array([[1., 2.],
       [3., 4.]])

In [22]:
# convert numpy array to a torch tensor using torch.from_numpy
y = t.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

d/b .from_numpy  it uses the same space & .tensor is creates a copy new space

In [23]:
z=t.tensor(x)
z

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [24]:
#convert a torch tensor to numpy array
u=y.numpy()
u

array([[1., 2.],
       [3., 4.]])